name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ['3.9', '3.8', '3.7']
    steps:
      - name: Cache Singularity
        id: cache-singularity
        uses: actions/cache@v2
        with:
          path: $HOME/singularity
          key: ${{ runner.os }}-singularity-3.6.2  # Change this if upgrading singularity
          restore-keys: |
            ${{ runner.os }}-singularity-
      - name: Install Singularity
        if: steps.cache-singularity.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends \
            libssl-dev \
            uuid-dev \
            libgpgme11-dev \
            squashfs-tools
          curl -fsSL https://github.com/hpcng/singularity/releases/download/v3.6.2/singularity-3.6.2.tar.gz \
          | tar xz
          cd singularity
          ./mconfig --prefix=$HOME/singularity
          cd builddir
          make -j
          sudo make install
      - name: Add Singularity to PATH
        run: echo $HOME/singularity >> $GITHUB_PATH
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install reproenv
        run: python -m pip install --editable .[dev]
      - name: Check types
        run: mypy reproenv
      - name: Check style
        run: flake8 reproenv
      - name: Run python tests
        run: pytest
      - name: Get code coverage
        run: codecov
